id: P921E7742
initial_creation_type: input
source_metadata:
  Title: Gilgit Manuscripts
  Editor: Dutt, Nalinaksa
  Publisher: Sri Satguru Publications
  Place of Publication: Delhi
  Year: '1984'
  Āryaśrīmahādevīvyākaraṇam:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T15:56:04.414850'
last_modified_at: '2022-03-08T15:56:04.414862'
